-- Production security hardening: profiles, RBAC overrides, partner scopes,
-- Storage isolation and client audit constraints.

-- ---------------------------------------------------------------------------
-- Profile privilege hardening
-- ---------------------------------------------------------------------------
drop policy if exists profiles_insert_own on public.profiles;
drop policy if exists profiles_update_own_or_admin on public.profiles;

create policy profiles_update_own_safe
on public.profiles for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy profiles_admin_update
on public.profiles for update to authenticated
using (public.is_admin())
with check (public.is_admin());

-- RLS controls rows; column grants prevent users from changing role/status.
revoke insert, update, delete on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant update (name, phone, avatar_path) on public.profiles to authenticated;

-- ---------------------------------------------------------------------------
-- User-specific permission overrides
-- ---------------------------------------------------------------------------
create table if not exists public.user_permissions (
  user_id uuid not null references auth.users(id) on delete cascade,
  permission_code text not null references public.permissions(code) on delete cascade,
  allowed boolean not null default true,
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (user_id, permission_code)
);

alter table public.user_permissions enable row level security;
create policy user_permissions_self_read on public.user_permissions
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy user_permissions_admin_all on public.user_permissions
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy roles_superadmin_write on public.roles
for all to authenticated using (public.is_superadmin()) with check (public.is_superadmin());
create policy permissions_superadmin_write on public.permissions
for all to authenticated using (public.is_superadmin()) with check (public.is_superadmin());
create policy role_permissions_superadmin_write on public.role_permissions
for all to authenticated using (public.is_superadmin()) with check (public.is_superadmin());

create or replace function public.has_permission(permission_code text)
returns boolean
language sql stable security definer set search_path = public
as $$
  select coalesce(
    (select up.allowed from public.user_permissions up
     where up.user_id = auth.uid() and up.permission_code = $1),
    exists (
      select 1 from public.role_permissions rp
      where rp.role_code = public.current_role()
        and rp.permission_code = $1
    ),
    false
  );
$$;

-- ---------------------------------------------------------------------------
-- Disable public self-signup at the database boundary.
-- Admin-created users carry app_metadata.provisioned_by; bootstrap carries
-- app_metadata.bootstrap. Public clients cannot write app_metadata.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  provisioner uuid;
  is_bootstrap boolean := coalesce((new.raw_app_meta_data ->> 'bootstrap')::boolean, false);
begin
  if is_bootstrap then
    perform pg_advisory_xact_lock(74202601);
    if exists (select 1 from public.profiles where role = 'superadmin' and active) then
      raise exception 'System already initialized';
    end if;
  else
    begin
      provisioner := nullif(new.raw_app_meta_data ->> 'provisioned_by', '')::uuid;
    exception when invalid_text_representation then
      provisioner := null;
    end;
    if provisioner is null or not exists (
      select 1 from public.profiles
      where id = provisioner and role in ('admin', 'superadmin') and active
    ) then
      raise exception 'Public signup is disabled';
    end if;
  end if;

  insert into public.profiles(id, username, name, email, role, active)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    new.email,
    'student',
    true
  );
  return new;
end;
$$;

-- Username resolution is server-only to prevent email enumeration.
revoke execute on function public.resolve_login_email(text) from anon, authenticated;
grant execute on function public.resolve_login_email(text) to service_role;

-- Student numbers can only be generated by privileged server code.
revoke execute on function public.generate_student_id() from authenticated;
grant execute on function public.generate_student_id() to service_role;

-- ---------------------------------------------------------------------------
-- Partner organization, validity and access scope
-- ---------------------------------------------------------------------------
alter table public.partner_users
  add column if not exists contact text not null default '',
  add column if not exists scope text not null default 'viewer',
  add column if not exists statut text not null default 'actif',
  add column if not exists date_debut date not null default current_date,
  add column if not exists date_fin date;

alter table public.partner_users
  drop constraint if exists partner_users_scope_check,
  add constraint partner_users_scope_check check (scope in ('viewer','academic','finance','institutional')),
  drop constraint if exists partner_users_statut_check,
  add constraint partner_users_statut_check check (statut in ('actif','inactif','suspendu')),
  drop constraint if exists partner_users_dates_check,
  add constraint partner_users_dates_check check (date_fin is null or date_fin >= date_debut);

create table if not exists public.partner_organization_formations (
  organization_id uuid not null references public.partners_organizations(id) on delete cascade,
  formation_id uuid not null references public.formations(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (organization_id, formation_id)
);

alter table public.partner_organization_formations enable row level security;
create policy partner_org_formations_own_read on public.partner_organization_formations
for select to authenticated using (
  organization_id in (
    select organization_id from public.partner_users
    where user_id = auth.uid()
  ) or public.is_admin()
);
create policy partner_org_formations_admin_all on public.partner_organization_formations
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace function public.partner_account_active()
returns boolean language sql stable security definer set search_path = public
as $$
  select coalesce(exists (
    select 1 from public.partner_users pu
    join public.profiles p on p.id = pu.user_id
    where pu.user_id = auth.uid()
      and p.role in ('partner','partner_admin')
      and p.active
      and pu.statut = 'actif'
      and pu.date_debut <= current_date
      and (pu.date_fin is null or pu.date_fin >= current_date)
  ), false);
$$;

create or replace function public.current_partner_scope()
returns text language sql stable security definer set search_path = public
as $$
  select pu.scope from public.partner_users pu
  where pu.user_id = auth.uid() and public.partner_account_active()
  limit 1;
$$;

create or replace function public.partner_has_scope(scopes text[])
returns boolean language sql stable security definer set search_path = public
as $$ select coalesce(public.current_partner_scope() = any(scopes), false); $$;

create or replace function public.partner_can_access_formation(p_formation_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$
  select coalesce(public.partner_account_active() and exists (
    select 1
    from public.partner_users pu
    join public.partner_organization_formations pof
      on pof.organization_id = pu.organization_id
    where pu.user_id = auth.uid() and pof.formation_id = p_formation_id
  ), false);
$$;

-- Organization records are not public contact directories.
drop policy if exists partners_organizations_public_read on public.partners_organizations;
drop policy if exists partner_read_own_organization on public.partners_organizations;
create policy partner_read_own_organization on public.partners_organizations
for select to authenticated using (
  id in (select organization_id from public.partner_users where user_id = auth.uid())
  or public.is_admin()
);

-- Explicit partner SELECT policies. No partner write policy is created.
create policy partner_students_read on public.students for select to authenticated
using (
  public.partner_has_scope(array['academic','institutional'])
  and public.partner_can_access_formation(formation_id)
);

create policy partner_teachers_read on public.teachers for select to authenticated
using (
  public.partner_has_scope(array['academic','institutional'])
  and exists (
    select 1 from public.teacher_modules tm
    join public.modules m on m.id = tm.module_id
    where tm.teacher_id = teachers.id
      and public.partner_can_access_formation(m.formation_id)
  )
);

create policy partner_schedule_read on public.schedule for select to authenticated
using (
  public.partner_has_scope(array['academic','institutional'])
  and public.partner_can_access_formation(formation_id)
);

create policy partner_attendance_read on public.attendance for select to authenticated
using (
  public.partner_has_scope(array['academic','institutional'])
  and exists (
    select 1 from public.students s
    where s.id = attendance.student_id
      and public.partner_can_access_formation(s.formation_id)
  )
);

create policy partner_courses_read on public.courses for select to authenticated
using (
  publie
  and public.partner_has_scope(array['academic','institutional'])
  and public.partner_can_access_formation(
    coalesce(formation_id, (select formation_id from public.modules where id = courses.module_id))
  )
);

create policy partner_course_files_read on public.course_files for select to authenticated
using (
  course_id in (select id from public.courses)
  and public.partner_has_scope(array['academic','institutional'])
);

create policy partner_tests_read on public.tests for select to authenticated
using (
  publie
  and public.partner_has_scope(array['academic','institutional'])
  and public.partner_can_access_formation(
    (select formation_id from public.modules where id = tests.module_id)
  )
);

create policy partner_grades_read on public.grades for select to authenticated
using (
  public.partner_has_scope(array['academic','institutional'])
  and exists (
    select 1 from public.students s
    where s.id = grades.student_id
      and public.partner_can_access_formation(s.formation_id)
  )
);

create policy partner_certificates_read on public.certificates for select to authenticated
using (
  public.partner_has_scope(array['institutional'])
  and public.partner_can_access_formation(formation_id)
);

create policy partner_scholarships_read on public.scholarships for select to authenticated
using (
  public.partner_has_scope(array['institutional'])
  and exists (
    select 1 from public.students s
    where s.id = scholarships.student_id
      and public.partner_can_access_formation(s.formation_id)
  )
);

create policy partner_payments_read on public.payments for select to authenticated
using (
  public.partner_has_scope(array['finance','institutional'])
  and exists (
    select 1 from public.students s
    where s.id = payments.student_id
      and public.partner_can_access_formation(s.formation_id)
  )
);

-- ---------------------------------------------------------------------------
-- Partner-safe views (only approved columns)
-- ---------------------------------------------------------------------------
create or replace view public.partner_schedule_view with (security_invoker = true) as
select sc.id, sc.jour, sc.date, sc.heure_debut, sc.heure_fin, sc.salle,
       f.name as formation_name, m.titre as module_name,
       concat(t.prenom, ' ', t.nom) as teacher_name
from public.schedule sc
join public.formations f on f.id = sc.formation_id
join public.modules m on m.id = sc.module_id
join public.teachers t on t.id = sc.teacher_id;

create or replace view public.partner_test_view with (security_invoker = true) as
select t.id, t.titre, t.duree, t.niveau, t.date_debut, t.date_fin,
       m.titre as module_name, f.name as formation_name
from public.tests t
join public.modules m on m.id = t.module_id
join public.formations f on f.id = m.formation_id
where t.publie;

create or replace view public.partner_grade_view with (security_invoker = true) as
select g.id, g.student_id, g.note, g.appreciation, g.date,
       s.nom, s.prenom, m.titre as module_name, f.name as formation_name
from public.grades g
join public.students s on s.id = g.student_id
join public.modules m on m.id = g.module_id
join public.formations f on f.id = s.formation_id;

create or replace view public.partner_scholarship_view with (security_invoker = true) as
select sc.id, sc.student_id, sc.statut, sc.date, sc.date_attribution,
       s.nom, s.prenom, f.name as formation_name
from public.scholarships sc
join public.students s on s.id = sc.student_id
join public.formations f on f.id = s.formation_id;

create or replace view public.partner_module_view with (security_invoker = true) as
select m.id, m.numero, m.titre, m.icon, m.description, m.duree,
       f.id as formation_id, f.name as formation_name, f.code as formation_code
from public.modules m
join public.formations f on f.id = m.formation_id
where m.active
  and (public.is_admin() or public.partner_can_access_formation(m.formation_id));

create or replace view public.partner_report_view with (security_invoker = true) as
select
  (select count(*) from public.students)::integer as total_students,
  (select count(*) from public.teachers)::integer as total_teachers,
  (select count(*) from public.modules m where m.active and (public.is_admin() or public.partner_can_access_formation(m.formation_id)))::integer as active_modules,
  (select count(*) from public.attendance)::integer as total_attendance,
  (select count(*) from public.attendance where statut = 'present')::integer as total_present,
  (select count(*) from public.certificates)::integer as total_certificates;

revoke all on public.partner_student_view, public.partner_teacher_view,
  public.partner_course_view, public.partner_attendance_view,
  public.partner_certificate_view, public.partner_report_view,
  public.partner_schedule_view, public.partner_test_view,
  public.partner_grade_view, public.partner_scholarship_view from anon;
revoke all on public.partner_module_view from anon;
grant select on public.partner_student_view, public.partner_teacher_view,
  public.partner_course_view, public.partner_attendance_view,
  public.partner_certificate_view, public.partner_report_view,
  public.partner_schedule_view, public.partner_test_view,
  public.partner_grade_view, public.partner_scholarship_view to authenticated;
grant select on public.partner_module_view to authenticated;

-- ---------------------------------------------------------------------------
-- Client audit is constrained to a safe whitelist.
-- ---------------------------------------------------------------------------
drop policy if exists audit_logs_insert on public.audit_logs;
create or replace function public.record_client_audit(
  p_action text,
  p_entity_type text,
  p_entity_id text default null,
  p_description text default ''
) returns uuid
language plpgsql security definer set search_path = public
as $$
declare v_id uuid;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_action not in ('PARTNER_ACCESS','FILE_OPEN','FILE_DOWNLOAD','LOGOUT') then
    raise exception 'Audit action not allowed';
  end if;
  insert into public.audit_logs(user_id, action, entity_type, entity_id, description)
  values (auth.uid(), p_action, left(p_entity_type, 100), left(p_entity_id, 255), left(p_description, 1000))
  returning id into v_id;
  return v_id;
end;
$$;
grant execute on function public.record_client_audit(text,text,text,text) to authenticated;

-- ---------------------------------------------------------------------------
-- Storage policies: least privilege per bucket and path.
-- ---------------------------------------------------------------------------
drop policy if exists storage_authenticated_upload on storage.objects;
drop policy if exists storage_owner_read on storage.objects;
drop policy if exists storage_owner_update on storage.objects;
drop policy if exists storage_owner_delete on storage.objects;

create policy avatars_own_insert on storage.objects for insert to authenticated
with check (
  bucket_id = 'avatars'
  and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
);
create policy avatars_own_read on storage.objects for select to authenticated
using (bucket_id = 'avatars' and (owner_id = auth.uid()::text or public.is_admin()));
create policy avatars_own_update on storage.objects for update to authenticated
using (bucket_id = 'avatars' and (owner_id = auth.uid()::text or public.is_admin()))
with check (bucket_id = 'avatars' and (owner_id = auth.uid()::text or public.is_admin()));
create policy avatars_own_delete on storage.objects for delete to authenticated
using (bucket_id = 'avatars' and (owner_id = auth.uid()::text or public.is_admin()));

create policy course_files_staff_insert on storage.objects for insert to authenticated
with check (bucket_id = 'course-files' and (public.current_role() = 'teacher' or public.is_admin()));
create policy course_files_authorized_storage_read on storage.objects for select to authenticated
using (
  bucket_id = 'course-files'
  and exists (select 1 from public.course_files cf where cf.storage_key = name)
);
create policy course_files_staff_delete on storage.objects for delete to authenticated
using (bucket_id = 'course-files' and (owner_id = auth.uid()::text or public.is_admin()));

create policy submissions_own_insert on storage.objects for insert to authenticated
with check (
  bucket_id = 'submission-files'
  and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
);
create policy submissions_authorized_storage_read on storage.objects for select to authenticated
using (
  bucket_id = 'submission-files'
  and (owner_id = auth.uid()::text or public.is_admin()
       or exists (select 1 from public.submission_files sf where sf.storage_key = name))
);

create policy certificates_admin_insert on storage.objects for insert to authenticated
with check (bucket_id = 'certificates' and public.is_admin());
create policy certificates_authorized_read on storage.objects for select to authenticated
using (
  bucket_id = 'certificates'
  and exists (select 1 from public.certificates c where c.file_path = name)
);

create policy enia_media_admin_write on storage.objects for insert to authenticated
with check (bucket_id = 'enia-media' and public.is_admin());
create policy enia_media_authenticated_read on storage.objects for select to authenticated
using (bucket_id = 'enia-media');

create policy public_media_admin_insert on storage.objects for insert to authenticated
with check (bucket_id = 'public-media' and public.is_admin());
create policy public_media_admin_update on storage.objects for update to authenticated
using (bucket_id = 'public-media' and public.is_admin())
with check (bucket_id = 'public-media' and public.is_admin());
create policy public_media_admin_delete on storage.objects for delete to authenticated
using (bucket_id = 'public-media' and public.is_admin());

create index if not exists partner_org_formations_formation_idx
on public.partner_organization_formations(formation_id, organization_id);